f_name = input("Enter first name")
l_name = input("enter last name")
age = input("enter your age") 
c_name = input("enter your city")
course = input("enter your course")
clg = input("enter your college")
skills = input("enter your skills")
hobbies = input("enter your hobbies")
full_name = "{} {}".format(f_name,l_name) 
dream = input("enetr your dream")     
print(f"Good evening sir this is {full_name}.","I'm from  "+c_name, "Currently i'm pursing "+course ,"from"+clg ," my hobbeis are {}.".format(hobbies), "I Want to Become a {} .".format(dream))